#!/usr/bin/env bash
# One-shot setup of the whole app (API + worker + dashboard) on a single Ubuntu server – written for an
# Oracle Cloud "Always Free" VM (VM.Standard.A1.Flex, arm64, or VM.Standard.E2.1.Micro, x86_64) but works on any Ubuntu 22.04/24.04 box.
#
#   sudo DOMAIN=chheda-rate.duckdns.org EMAIL=you@example.com bash deploy/oracle/setup.sh
#
# Re-running is safe: it updates the code, rebuilds, and restarts. Secrets already in /opt/chheda/app/.env are kept.
# Full guide: docs/DEPLOY-ORACLE.md
set -euo pipefail

DOMAIN="${DOMAIN:-}"                       # public host name that points at this server (DuckDNS or your own domain)
EMAIL="${EMAIL:-}"                         # for Let's Encrypt expiry notices (optional)
REPO="${REPO:-https://github.com/apar-ag3ncy/gold-rate.git}"
BRANCH="${BRANCH:-main}"
APP_USER=chheda
APP_DIR=/opt/chheda/app
LOG_DIR=/var/log/chheda
NODE_MAJOR="${NODE_MAJOR:-24}"

say()  { printf '\n\033[1;32m==> %s\033[0m\n' "$*"; }
warn() { printf '\n\033[1;33m!! %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run with sudo:  sudo DOMAIN=... bash deploy/oracle/setup.sh"
[[ -n "$DOMAIN" ]] || die "DOMAIN is required, e.g.  sudo DOMAIN=chheda-rate.duckdns.org bash deploy/oracle/setup.sh"
[[ "$DOMAIN" =~ ^[a-z0-9.-]+$ ]] || die "DOMAIN must be a plain host name (no https://, no slash)"
command -v apt-get >/dev/null || die "this script is for Ubuntu / Debian"
export DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------- 1. swap (the free micro VM has 1 GB RAM; next build needs more)
MEM_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
if [[ $MEM_MB -lt 3000 ]] && ! swapon --show | grep -q .; then
  say "Adding 2 GB swap (RAM is ${MEM_MB} MB)"
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ---------------------------------------------------------------- 2. packages + Node
say "Installing packages"
apt-get update -qq
apt-get install -y -qq nginx certbot python3-certbot-nginx git curl ca-certificates gnupg iptables-persistent >/dev/null
if ! command -v node >/dev/null || [[ "$(node -v | cut -c2- | cut -d. -f1)" -lt "$NODE_MAJOR" ]]; then
  say "Installing Node.js $NODE_MAJOR"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null
  apt-get install -y -qq nodejs >/dev/null
fi
say "Node $(node -v), npm $(npm -v), $(uname -m)"

# ---------------------------------------------------------------- 3. firewall: Oracle's Ubuntu image blocks everything except SSH in iptables
say "Opening ports 80 and 443"
for port in 80 443; do
  iptables -C INPUT -p tcp -m state --state NEW -m tcp --dport "$port" -j ACCEPT 2>/dev/null \
    || iptables -I INPUT 1 -p tcp -m state --state NEW -m tcp --dport "$port" -j ACCEPT
done
netfilter-persistent save >/dev/null 2>&1 || warn "could not persist iptables rules (netfilter-persistent) – re-run this step after a reboot if the site stops answering"
if command -v ufw >/dev/null && ufw status | grep -q '^Status: active'; then ufw allow 'Nginx Full' >/dev/null; fi

# ---------------------------------------------------------------- 4. user, folders, code
id -u $APP_USER >/dev/null 2>&1 || useradd -m -s /bin/bash $APP_USER
mkdir -p /opt/chheda "$LOG_DIR" /var/backups/chheda
chown -R $APP_USER:$APP_USER /opt/chheda "$LOG_DIR" /var/backups/chheda
if [[ -d "$APP_DIR/.git" ]]; then
  say "Updating code ($BRANCH)"
  sudo -u $APP_USER git -C "$APP_DIR" fetch --quiet origin "$BRANCH"
  sudo -u $APP_USER git -C "$APP_DIR" checkout --quiet "origin/$BRANCH"
else
  say "Cloning $REPO"
  sudo -u $APP_USER git clone --quiet --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
mkdir -p "$APP_DIR/uploads" && chown $APP_USER:$APP_USER "$APP_DIR/uploads"
say "Installing dependencies (a few minutes the first time)"
sudo -u $APP_USER bash -c "cd '$APP_DIR' && npm ci --no-audit --no-fund --loglevel=error"

# ---------------------------------------------------------------- 5. .env (created once; secrets generated here never leave the server)
ENV_FILE="$APP_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  say "Creating $ENV_FILE"
  MONGO_URI="${MONGO_URI:-}"
  if [[ -z "$MONGO_URI" ]]; then
    echo "Paste your MongoDB Atlas connection string (mongodb+srv://USER:PASSWORD@.../chheda_gold) and press Enter:"
    read -r MONGO_URI </dev/tty
  fi
  [[ "$MONGO_URI" == mongodb* ]] || die "that does not look like a MongoDB connection string"
  ADMIN_EMAIL="${ADMIN_EMAIL:-}"
  if [[ -z "$ADMIN_EMAIL" ]]; then
    echo "Owner's email address (the dashboard runs as this user – there is no login screen):"
    read -r ADMIN_EMAIL </dev/tty
  fi
  [[ "$ADMIN_EMAIL" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]] || die "that does not look like an email address"
  cat > "$ENV_FILE" <<ENV
# Production settings – generated by deploy/oracle/setup.sh on $(date -Is). Keep this file private (chmod 600).
NODE_ENV=production
API_PORT=4000
WORKER_PORT=4100
MONGO_URI=$MONGO_URI
WEB_ORIGIN=https://$DOMAIN
WEB_PUBLIC_URL=https://$DOMAIN
API_INTERNAL_URL=http://127.0.0.1:4000
# No login screen: everyone who opens https://$DOMAIN acts as this user. Keep the address private.
AUTO_LOGIN_EMAIL=$ADMIN_EMAIL
# images are rendered on this server and served at https://$DOMAIN/media/… (Instagram downloads them from there)
STORAGE_DRIVER=local
MEDIA_DIR=$APP_DIR/uploads
MEDIA_BASE_URL=https://$DOMAIN
ENCRYPTION_KEY=$(openssl rand -base64 32)
SESSION_TTL_HOURS=12
# Nothing is posted to Instagram / WhatsApp while DRY_RUN=true. Switch to false only when the Meta app is live (docs/GO-LIVE.md).
DRY_RUN=true
META_GRAPH_VERSION=v21.0
META_APP_ID=
META_APP_SECRET=
META_WEBHOOK_VERIFY_TOKEN=$(openssl rand -hex 24)
WA_SEND_CONCURRENCY=5
WA_SEND_DELAY_MS=100
IG_PUBLISH_TIMEOUT_MS=120000
# Alert emails (optional): fill SMTP_* to get an email when a post fails or no rate is approved.
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_FROM="Chheda Gold Rate <alerts@$DOMAIN>"
SENTRY_DSN=
# IBJA benchmark: website = read ibjarates.com (trial). With an official key: IBJA_SOURCE=api and IBJA_API_TOKEN=...
IBJA_SOURCE=website
IBJA_API_TOKEN=
IBJA_API_BASE=https://ibjarates.com
ENV
  chown $APP_USER:$APP_USER "$ENV_FILE" && chmod 600 "$ENV_FILE"
else
  say "Keeping existing $ENV_FILE"
  grep -q "^WEB_ORIGIN=https://$DOMAIN\$" "$ENV_FILE" || warn "WEB_ORIGIN in .env is not https://$DOMAIN – the dashboard will reject requests until it matches"
  ADMIN_EMAIL=$(grep -E '^AUTO_LOGIN_EMAIL=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' || true)
fi
echo "APP_VERSION=$(sudo -u $APP_USER git -C "$APP_DIR" rev-parse --short HEAD)" > "$APP_DIR/.env.version"; chown $APP_USER:$APP_USER "$APP_DIR/.env.version"
say "Checking .env"
sudo -u $APP_USER bash -c "cd '$APP_DIR' && node_modules/.bin/tsx apps/api/scripts/check-env.mjs .env"

# ---------------------------------------------------------------- 6. the dashboard user (created once; the password is random and never needed – there is no login screen)
if [[ -n "${ADMIN_EMAIL:-}" ]]; then
  say "Dashboard user $ADMIN_EMAIL"
  GEN_PASSWORD="Aa1$(openssl rand -base64 24 | tr -d '/+=')"
  sudo -u $APP_USER env SEED_ADMIN_EMAIL="$ADMIN_EMAIL" SEED_ADMIN_PASSWORD="$GEN_PASSWORD" bash -c "cd '$APP_DIR' && npm run seed --silent" \
    || warn "could not create the user – run later:  cd $APP_DIR && sudo -u chheda env SEED_ADMIN_EMAIL=$ADMIN_EMAIL SEED_ADMIN_PASSWORD='<10+ chars, Aa1>' npm run seed"
else
  warn "AUTO_LOGIN_EMAIL is empty in $ENV_FILE – the dashboard will show 'Not signed in' until you set it and restart chheda-api"
fi

# ---------------------------------------------------------------- 7. build the dashboard
say "Building the dashboard (2–5 minutes)"
sudo -u $APP_USER bash -c "cd '$APP_DIR' && NODE_ENV=production API_INTERNAL_URL=http://127.0.0.1:4000 NEXT_TELEMETRY_DISABLED=1 npm run build:web --silent"

# ---------------------------------------------------------------- 8. services
say "Installing services"
# deploy.sh runs as chheda and restarts the services – allow exactly those commands without a password
cat > /etc/sudoers.d/chheda-deploy <<'SUDO'
chheda ALL=(root) NOPASSWD: /usr/bin/systemctl restart chheda-api chheda-worker chheda-web, /usr/bin/systemctl restart chheda-api chheda-worker, /usr/bin/systemctl restart chheda-api, /usr/bin/systemctl restart chheda-worker, /usr/bin/systemctl restart chheda-web, /usr/bin/systemctl status chheda-api, /usr/bin/systemctl status chheda-worker, /usr/bin/systemctl status chheda-web
SUDO
chmod 440 /etc/sudoers.d/chheda-deploy && visudo -cf /etc/sudoers.d/chheda-deploy >/dev/null
cp "$APP_DIR"/deploy/systemd/chheda-api.service "$APP_DIR"/deploy/systemd/chheda-worker.service "$APP_DIR"/deploy/systemd/chheda-web.service /etc/systemd/system/
cp "$APP_DIR"/deploy/logrotate/chheda /etc/logrotate.d/chheda
systemctl daemon-reload
systemctl enable --now chheda-api chheda-worker chheda-web >/dev/null
systemctl restart chheda-api chheda-worker chheda-web

# ---------------------------------------------------------------- 9. nginx + https
say "Configuring nginx for https://$DOMAIN"
cp "$APP_DIR"/deploy/nginx/chheda-http.conf /etc/nginx/conf.d/chheda-http.conf
cp "$APP_DIR"/deploy/nginx/chheda-proxy.conf /etc/nginx/snippets/chheda-proxy.conf
sed "s/__DOMAIN__/$DOMAIN/g" "$APP_DIR"/deploy/nginx/chheda-site.conf > /etc/nginx/sites-available/chheda.conf
ln -sf /etc/nginx/sites-available/chheda.conf /etc/nginx/sites-enabled/chheda.conf
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
if [[ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then
  say "Requesting the https certificate (Let's Encrypt)"
  if [[ -n "$EMAIL" ]]; then CERT_MAIL=(-m "$EMAIL"); else CERT_MAIL=(--register-unsafely-without-email); fi
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --redirect "${CERT_MAIL[@]}" \
    || die "certificate failed. Usual causes: $DOMAIN does not point at this server's public IP yet, or port 80 is not open in the Oracle security list. Fix it and re-run this script."
fi
nginx -t && systemctl reload nginx

# ---------------------------------------------------------------- 10. backups (optional – mongodump for Atlas)
if ! command -v mongodump >/dev/null; then
  say "Installing mongodump for nightly backups"
  CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
  ( curl -fsSL https://pgp.mongodb.com/server-8.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-8.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/mongodb-8.gpg] https://repo.mongodb.org/apt/ubuntu $CODENAME/mongodb-org/8.0 multiverse" > /etc/apt/sources.list.d/mongodb-8.list \
    && apt-get update -qq && apt-get install -y -qq mongodb-database-tools >/dev/null ) || warn "mongodump not installed – nightly backups skipped (Atlas paid tiers have their own backups)"
fi
if command -v mongodump >/dev/null; then
  ( sudo -u $APP_USER crontab -l 2>/dev/null | grep -v mongodump.sh; echo "30 2 * * * $APP_DIR/deploy/backup/mongodump.sh >> $LOG_DIR/backup.log 2>&1" ) | sudo -u $APP_USER crontab -
fi

# ---------------------------------------------------------------- 11. check
say "Checking"
sleep 6
ok=1
curl -fsS http://127.0.0.1:4000/health >/dev/null && echo "  API      ok" || { echo "  API      FAILED  (tail $LOG_DIR/api.log)"; ok=0; }
curl -fsS http://127.0.0.1:4100/health >/dev/null && echo "  worker   ok" || { echo "  worker   FAILED  (tail $LOG_DIR/worker.log)"; ok=0; }
curl -fsS -o /dev/null http://127.0.0.1:3000/login && echo "  web      ok" || { echo "  web      FAILED  (tail $LOG_DIR/web.log)"; ok=0; }
curl -fsS -o /dev/null "https://$DOMAIN/login" && echo "  https    ok" || { echo "  https    not reachable yet from this machine (DNS may still be updating)"; }
[[ $ok -eq 1 ]] || die "something did not start – see the log named above"
say "Done. Open https://$DOMAIN – it opens straight on the Rate page (no login). Keep the address private."
echo "  update later:  ssh ubuntu@<server>  →  cd $APP_DIR && sudo -u chheda ./deploy/deploy.sh"
