// Regenerates src/services/creative/fontData.ts from assets/fonts (run after changing a font file):  node apps/api/scripts/embed-fonts.mjs
// The fonts are embedded so the renderer works inside any bundle (Next.js on Vercel) without relying on file paths.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const files = ['Marcellus-Regular.ttf', 'Poppins-Regular.ttf', 'Poppins-SemiBold.ttf'];
const entries = files.map((f) => `  '${f}': '${readFileSync(join(root, 'assets/fonts', f)).toString('base64')}',`);
writeFileSync(join(root, 'src/services/creative/fontData.ts'),
  `// GENERATED by scripts/embed-fonts.mjs from assets/fonts – do not edit. Marcellus + Poppins, SIL Open Font License (see assets/fonts/OFL-*.txt).\nexport const FONT_FILES: Record<string, string> = {\n${entries.join('\n')}\n};\n`);
console.log(`embedded ${files.length} fonts`);
